apiVersion: v1
kind: Secret
metadata:
  name: go-otel-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "your-secure-password-here"  # Ganti dengan password yang aman
